@baseUrl = http://localhost:3000
@clientId = 1636894873

### Test Valid Authorization Request
GET {{baseUrl}}/oauth/authorize?response_type=code&client_id={{clientId}}&redirect_uri=http://localhost:3000/callback

### Test Missing Client ID
GET {{baseUrl}}/oauth/authorize?response_type=code&redirect_uri=http://localhost:3000/callback


### Test Missing Response Type
GET {{baseUrl}}/oauth/authorize?client_id={{clientId}}&redirect_uri=http://localhost:3000/callback

### Test Invalid Response Type
GET {{baseUrl}}/oauth/authorize?response_type=invalid&client_id={{clientId}}&redirect_uri=http://localhost:3000/callback